export const AppCategoryLabels = {
    SocialMedia: "Social Media",
    Messaging: "Messaging",
    Gaming: "Gaming",
    PeerToPeer: "P2P / File Sharing",
    DarkWeb: "Dark Web / Anonymity",
    VPN: "VPN",
    VirtualMachine: "Virtual Machine",
    WebBrowser: "Browser",
    CloudStorage: "Cloud Storage",
    CryptoPayment: "Crypto / Payment",
    Cleaner: "System Cleaner",
    Encryption: "Encryption",
    AntiForensics: "Anti-Forensic",
    RemoteAccess: "Remote Access",
    Utilities: "Utilities",
    Productivity: "Productivity",
    Development: "Development",
    Multimedia: "Multimedia",
    Unknown: "Unknown"
};
export const AppCategoryColors = {
    SocialMedia: "var(--color-info)",
    Messaging: "var(--color-info)",
    Gaming: "var(--color-success)",
    PeerToPeer: "var(--color-danger)",
    DarkWeb: "var(--color-danger)",
    VPN: "var(--color-accent-amber)",
    VirtualMachine: "var(--color-accent-amber)",
    WebBrowser: "var(--color-success)",
    CloudStorage: "var(--color-accent-amber)",
    CryptoPayment: "var(--color-accent-amber)",
    Cleaner: "var(--color-danger)",
    Encryption: "var(--color-accent-amber)",
    AntiForensics: "var(--color-danger)",
    RemoteAccess: "var(--color-accent-amber)",
    Utilities: "var(--color-success)",
    Productivity: "var(--color-success)",
    Development: "var(--color-success)",
    Multimedia: "var(--color-success)",
    Unknown: "var(--color-text-muted)"
};
export const AppCategoryRiskLevels = {
    SocialMedia: "MEDIUM",
    Messaging: "MEDIUM",
    Gaming: "LOW",
    PeerToPeer: "HIGH",
    DarkWeb: "CRITICAL",
    VPN: "HIGH",
    VirtualMachine: "HIGH",
    WebBrowser: "LOW",
    CloudStorage: "MEDIUM",
    CryptoPayment: "HIGH",
    Cleaner: "CRITICAL",
    Encryption: "HIGH",
    AntiForensics: "CRITICAL",
    RemoteAccess: "HIGH",
    Utilities: "LOW",
    Productivity: "LOW",
    Development: "LOW",
    Multimedia: "LOW",
    Unknown: "UNKNOWN"
};
